# Generated by Django 4.1 on 2022-08-31 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=20)),
                ('account', models.CharField(max_length=100)),
                ('expense_type', models.CharField(max_length=100)),
                ('accounting_voucher', models.CharField(max_length=100)),
                ('budget', models.CharField(max_length=100)),
                ('contract', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('applicant', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=20)),
                ('account', models.CharField(max_length=100)),
                ('income_type', models.CharField(max_length=100)),
                ('accounting_voucher', models.CharField(max_length=100)),
                ('budget', models.CharField(max_length=100)),
                ('contract', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('applicant', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
